import test from 'node:test';
import assert from 'node:assert/strict';
import { SerialConnection, DISPLAY_SETTLE_MS } from '../src/serial.js';
import { packImageToUSB40, imageToUSB40Handshake, validImageToUSB40Reply } from '../src/imagetousb40.js';
import { toCArray } from '../src/conversion.js';

const dimensions = { width: 800, height: 480, mode: 'mono' };
// Hand-calculated fixtures from the EXE's packet fields, not generated by the adapter.
const MONO_REQUEST = [0xaa, 0x55, 0xe1, 0xbb, 0x80, 2, 0xc4, 0, 0xe1, 0xff, 0x0d, 0x0a];
const ACK = Uint8Array.of(0xa0, 0x50, 0xf1, 0, 0, 0, 0, 0, 0xe1, 0xff);

function device(onWrite = (bytes, controller) => { if (bytes.length === 12) controller.enqueue(ACK); }) {
  const writes = [], times = [];
  let controller, cancelled = false;
  const readable = new ReadableStream({ start(c) { controller = c; }, cancel() { cancelled = true; } });
  const writable = new WritableStream({ async write(bytes) {
    writes.push(bytes.slice()); times.push(performance.now());
    await onWrite(bytes, controller);
  } });
  const port = {
    readable, writable,
    async open(options) { this.options = options; },
    async setSignals(signals) { this.signals = signals; },
    async close() { assert.equal(readable.locked, false); assert.equal(writable.locked, false); this.closed = true; },
    getInfo() { return { usbVendorId: 0x1a86, usbProductId: 0x7523 }; },
  };
  let clock = 0;
  const connection = new SerialConnection({ requestPort: async () => port }, { now: () => clock });
  return { connection, port, writes, times, controller, advance(ms) { clock += ms; }, get cancelled() { return cancelled; } };
}

test('v4 800x480 monochrome is white=1, black=0, left-to-right, top-to-bottom', () => {
  const pixels = new Uint8Array(800 * 480).fill(1);
  pixels.set([0, 1, 0, 1, 0, 1, 0, 1]); pixels[800] = 0; pixels[pixels.length - 1] = 0;
  const bytes = packImageToUSB40(pixels, 800, 480, 'mono');
  assert.equal(bytes.length, 48000);
  assert.equal(bytes[0], 0x55); assert.equal(bytes[99], 0xff); assert.equal(bytes[100], 0x7f); assert.equal(bytes.at(-1), 0xfe);
  assert.deepEqual([...imageToUSB40Handshake(bytes, dimensions)], MONO_REQUEST);
});

test('v4 tri-color includes red in BW plane and sends a separate active-low red plane', () => {
  const pixels = new Uint8Array(800 * 480).fill(1);
  pixels.set([0, 1, 2, 1, 0, 2, 1, 1]);
  const bytes = packImageToUSB40(pixels, 800, 480, 'tri');
  assert.equal(bytes.length, 96000); assert.equal(bytes[0], 0x77); assert.equal(bytes[48000], 0xdb);
  assert.equal(bytes[47999], 0xff); assert.equal(bytes[95999], 0xff);
  assert.deepEqual([...imageToUSB40Handshake(bytes, { ...dimensions, mode: 'tri' })],
    [0xaa, 0x55, 0xe1, 0xbb, 0x80, 3, 0xc4, 1, 0xe3, 0xff, 0x0d, 0x0a]);
  bytes.fill(0xff, 48000);
  const noRed = imageToUSB40Handshake(bytes, { ...dimensions, mode: 'tri' });
  assert.equal(noRed[7], 0); assert.equal(noRed[8], 0xe2);
});

test('v4 four-color codes are black=0, white=1, red=3, yellow=2, MSB-first', () => {
  const pixels = new Uint8Array(800 * 480).fill(1);
  pixels.set([0, 1, 2, 3]); pixels[800] = 3;
  const bytes = packImageToUSB40(pixels, 800, 480, 'four');
  assert.equal(bytes.length, 96000); assert.equal(bytes[0], 0x1e); assert.equal(bytes[1], 0x55); assert.equal(bytes[200], 0x95);
  assert.deepEqual([...imageToUSB40Handshake(bytes, { ...dimensions, mode: 'four' })],
    [0xaa, 0x55, 0xe1, 0xbb, 0x80, 4, 0xc4, 1, 0xe4, 0xff, 0x0d, 0x0a]);
  bytes[0] = 0x1a; // no red: black, white, yellow, yellow
  assert.equal(imageToUSB40Handshake(bytes, { ...dimensions, mode: 'four' })[7], 0);
});

test('unsupported dimensions, modes, malformed pixels, and payload lengths are blocked', async () => {
  assert.throws(() => packImageToUSB40(new Uint8Array(800 * 480), 800, 480, 'six'), /2, 3, or 4/);
  assert.throws(() => packImageToUSB40(new Uint8Array(400 * 300), 400, 300, 'mono'), /800 × 480/);
  assert.throws(() => packImageToUSB40(new Uint8Array(800 * 480).fill(2), 800, 480, 'mono'), /palette/);
  assert.throws(() => packImageToUSB40(new Uint8Array(1), 800, 480, 'mono'), /palette/);
  const m = device(); await m.connection.connect({ protocol: 'imagetousb40' });
  await assert.rejects(m.connection.send(new Uint8Array(1), dimensions), /size mismatch/);
  assert.equal(m.writes.length, 0); assert.equal(m.connection.tainted, false);
  await m.connection.disconnect();
});

test('v4 transfer waits for valid fragmented ACK then sends exact payload, delimiters and pauses', async () => {
  const m = device((bytes, c) => {
    if (bytes.length === 12) {
      c.enqueue(Uint8Array.of(0x00, 0xa0, 0xff)); // noise / overlapping invalid frame
      const bad = ACK.slice(); bad[8] ^= 1; c.enqueue(bad);
      c.enqueue(Uint8Array.of(0xa0, 0x50, 0xf2, 0, 0, 0, 0, 0, 0xe2, 0xff)); // not acceptance
      c.enqueue(ACK.slice(0, 3)); c.enqueue(ACK.slice(3));
    }
  });
  await m.connection.connect({ protocol: 'imagetousb40' });
  assert.deepEqual(m.port.signals, { requestToSend: true, dataTerminalReady: false });
  assert.equal(m.port.options.baudRate, 115200);
  const input = Uint8Array.from({ length: 48000 }, (_, i) => i % 251), progress = [], states = [];
  const result = await m.connection.send(input, { ...dimensions, onProgress: n => progress.push(n), onStatus: state => states.push(state.phase) });
  assert.deepEqual([...m.writes[0]], MONO_REQUEST);
  assert.deepEqual(states, ['handshake', 'accepted']);
  const payload = m.writes.slice(1).filter((_, i) => i % 2 === 0);
  assert.deepEqual(payload.map(b => b.length), [...Array(11).fill(4096), 2944]);
  assert.deepEqual(Uint8Array.from(payload.flatMap(b => [...b])), input);
  for (const delimiter of m.writes.slice(2).filter((_, i) => i % 2 === 0)) assert.deepEqual([...delimiter], [13, 10]);
  for (let i = 3; i < m.times.length; i += 2) assert.ok(m.times[i] - m.times[i - 1] >= 90, '100 ms vendor pacing');
  assert.equal(progress.at(-1), 48000);
  assert.deepEqual(result, { bytesSent: 48000, handshakeAccepted: true, refreshConfirmed: false });
  assert.equal(m.cancelled, false); assert.equal(m.port.readable.locked, true); assert.equal(m.port.writable.locked, false);
  // The input reader continues through refresh; another send must wait.
  m.advance(DISPLAY_SETTLE_MS);
  const abort = new AbortController();
  await assert.rejects(m.connection.send(input, { ...dimensions, signal: abort.signal, onStatus: s => { if (s.phase === 'accepted') abort.abort(); } }), { name: 'AbortError' });
  assert.equal(m.writes.length, 26); // first transfer's 25 writes, then only a second handshake
  await m.connection.disconnect();
  assert.equal(m.port.readable.locked, false);
});

test('the observed ASCII firmware output is diagnostic text, never a handshake or refresh ACK', async () => {
  const text = '7926fe:15\r\n81471fe:16\r\n82697fe:17\r\n82697The Endlen=8269710fe:0\r\n';
  const reply = new TextEncoder().encode(text);
  const m = device((bytes, c) => { c.enqueue(reply.slice(0, 17)); c.enqueue(reply.slice(17)); });
  await m.connection.connect({ protocol: 'imagetousb40' });
  await assert.rejects(m.connection.send(new Uint8Array(48000), { ...dimensions, handshakeTimeoutMs: 20 }), error => {
    assert.match(error.message, /Received 64 serial bytes/);
    assert.match(error.message, /The Endlen=82697/);
    assert.match(error.message, /No image pixels were sent/);
    return true;
  });
  assert.equal(m.writes.length, 1);
  assert.equal(m.connection.tainted, true);
  await m.connection.disconnect();
});

test('device output is drained during pixels and after transfer; an immediate resend writes nothing', async () => {
  const received = [];
  const m = device((bytes, c) => {
    if (bytes.length === 12) c.enqueue(ACK);
    else c.enqueue(new TextEncoder().encode('fe:15\r\n'));
  });
  await m.connection.connect({ protocol: 'imagetousb40', onReceive: bytes => received.push(bytes.slice()) });
  await m.connection.send(new Uint8Array(48000), dimensions);
  assert.equal(received.length, m.writes.length);
  assert.equal(m.connection.refreshRemainingMs, 25000);
  const count = m.writes.length;
  await assert.rejects(m.connection.send(new Uint8Array(48000), dimensions), /Wait 25 seconds/);
  assert.equal(m.writes.length, count);
  assert.equal(m.connection.tainted, false);
  m.controller.enqueue(new TextEncoder().encode('The Endlen=48000'));
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(new TextDecoder().decode(received.at(-1)), 'The Endlen=48000');
  // ASCII "The End" must not shorten the pause or establish physical refresh.
  assert.equal(m.connection.refreshRemainingMs, 25000);
  m.advance(DISPLAY_SETTLE_MS);
  const abort = new AbortController();
  await assert.rejects(m.connection.send(new Uint8Array(48000), { ...dimensions, signal: abort.signal,
    onStatus: s => { if (s.phase === 'accepted') abort.abort(); },
  }), { name: 'AbortError' });
  assert.equal(m.writes.length, count + 1);
  await m.connection.disconnect();
});

test('an ACK received while idle cannot authorize a later image', async () => {
  const m = device(() => {});
  await m.connection.connect({ protocol: 'imagetousb40' });
  m.controller.enqueue(ACK);
  await new Promise(resolve => setImmediate(resolve));
  await assert.rejects(m.connection.send(new Uint8Array(48000), { ...dimensions, handshakeTimeoutMs: 20 }), /No serial response received/);
  assert.equal(m.writes.length, 1);
  await m.connection.disconnect();
});

test('read failure after acceptance stops subsequent pixels and releases both locks', async () => {
  const m = device((bytes, c) => {
    if (bytes.length === 12) c.enqueue(ACK);
    else c.error(new Error('Device input failed during pixels'));
  });
  await m.connection.connect({ protocol: 'imagetousb40' });
  await assert.rejects(m.connection.send(new Uint8Array(48000), dimensions), /input failed during pixels/);
  assert.equal(m.writes.filter(b => b.length > 12).length, 1);
  assert.equal(m.connection.tainted, true);
  assert.equal(m.port.readable.locked, false);
  assert.equal(m.port.writable.locked, false);
  await m.connection.disconnect();
});

test('a failed handshake write clears its pending ACK wait and closes the reader', async () => {
  const m = device(() => { throw new Error('Header write failed'); });
  await m.connection.connect({ protocol: 'imagetousb40' });
  await assert.rejects(m.connection.send(new Uint8Array(48000), dimensions), /Header write failed/);
  assert.equal(m.connection.input.pending, null);
  assert.equal(m.port.readable.locked, false);
  assert.equal(m.port.writable.locked, false);
  await m.connection.disconnect();
});

test('disconnect during refresh cancels the persistent read but does not erase the waiting period', async () => {
  const m = device();
  await m.connection.connect({ protocol: 'imagetousb40' });
  await m.connection.send(new Uint8Array(48000), dimensions);
  await m.connection.disconnect();
  assert.equal(m.cancelled, true);
  assert.equal(m.port.readable.locked, false);
  assert.equal(m.connection.refreshRemainingMs, DISPLAY_SETTLE_MS);
  assert.equal(m.connection.input, null);
});

for (const mode of ['tri', 'four']) test(`v4 ${mode} sends all 96,000 bytes with no extra header between planes`, async () => {
  const m = device(); await m.connection.connect({ protocol: 'imagetousb40' });
  const bytes = packImageToUSB40(Uint8Array.from({ length: 384000 }, (_, i) => i % (mode === 'tri' ? 3 : 4)), 800, 480, mode);
  await m.connection.send(bytes, { ...dimensions, mode });
  const blocks = m.writes.slice(1).filter((_, i) => i % 2 === 0);
  assert.deepEqual(blocks.map(b => b.length), [...Array(23).fill(4096), 1792]);
  assert.deepEqual(Uint8Array.from(blocks.flatMap(b => [...b])), bytes);
  assert.equal(m.writes[0][3], 0xbb); assert.equal(m.writes[0][4], 0x80); // single-plane length even for color
  await m.connection.disconnect();
});

test('silence and checksum failures time out without sending image bytes; reconnect is required', async () => {
  for (const reply of [null, Uint8Array.of(0xa0, 0x50, 0xf1, 0, 0, 0, 0, 0, 0, 0xff)]) {
    const m = device((bytes, c) => { if (reply) c.enqueue(reply); });
    await m.connection.connect({ protocol: 'imagetousb40' });
    await assert.rejects(m.connection.send(new Uint8Array(48000), { ...dimensions, handshakeTimeoutMs: 20 }), /No valid ImageToUSB/);
    assert.equal(m.writes.length, 1); assert.equal(m.cancelled, true); assert.equal(m.connection.tainted, true);
    assert.equal(m.port.readable.locked, false); assert.equal(m.port.writable.locked, false);
    await assert.rejects(m.connection.send(new Uint8Array(48000), dimensions), /Reset the board/);
    await m.connection.disconnect();
  }
});

test('stop while waiting for handshake releases the read and sends no pixels', async () => {
  const abort = new AbortController();
  const m = device(() => setTimeout(() => abort.abort(), 5));
  await m.connection.connect({ protocol: 'imagetousb40' });
  await assert.rejects(m.connection.send(new Uint8Array(48000), { ...dimensions, signal: abort.signal }), { name: 'AbortError' });
  assert.equal(m.writes.length, 1); assert.equal(m.cancelled, true); assert.equal(m.connection.busy, false);
  await m.connection.disconnect();
});

test('read errors / unplug before handshake release locks without sending pixels', async () => {
  const m = device((bytes, c) => c.error(new Error('USB unplugged')));
  await m.connection.connect({ protocol: 'imagetousb40' });
  await assert.rejects(m.connection.send(new Uint8Array(48000), dimensions), /USB unplugged/);
  assert.equal(m.writes.length, 1); assert.equal(m.connection.tainted, true);
  await m.connection.disconnect();
});

test('stop during image pacing prevents all subsequent blocks', async () => {
  const m = device(), abort = new AbortController();
  await m.connection.connect({ protocol: 'imagetousb40' });
  await assert.rejects(m.connection.send(new Uint8Array(48000), { ...dimensions, signal: abort.signal, onProgress: () => setTimeout(() => abort.abort(), 5) }), { name: 'AbortError' });
  assert.equal(m.writes.length, 3); // handshake, one block, CRLF
  assert.equal(m.connection.tainted, true);
  await m.connection.disconnect();
});

test('failed RTS/DTR configuration closes the opened port', async () => {
  const m = device(); m.port.setSignals = async () => { throw new Error('Cannot set RTS'); };
  await assert.rejects(m.connection.connect({ protocol: 'imagetousb40' }), /Cannot set RTS/);
  assert.equal(m.port.closed, true); assert.equal(m.connection.port, null); assert.equal(m.connection.busy, false);
});

test('v4 exported C payload names the correct encoding and excludes serial framing', () => {
  const output = toCArray(Uint8Array.of(0x1e), { ...dimensions, mode: 'four', protocol: 'imagetousb40' });
  assert.match(output, /ImageToUSB v4.0/); assert.match(output, /red=3, yellow=2/);
  assert.match(output, /epd_image_length = 1/); assert.match(output, /0x1e/);
  assert.equal(validImageToUSB40Reply(ACK), true);
});
